### ISSUE TITLE
camera move far from scene app must crushed

### ISSUE THREAD

**Issue by houtie** [rawrunprotected/rasterizer#1]
// Main.cpp line 186
// Sort front to back
#ifdef BUG
    std::sort(begin(g_occluders), end(g_occluders), [&](const auto& o1, const auto& o2) {
      __m128 dist1 = _mm_sub_ps(o1->m_center, g_cameraPosition);
      __m128 dist2 = _mm_sub_ps(o2->m_center, g_cameraPosition);
      return _mm_comile_ss(_mm_dp_ps(dist1, dist1, 0x7f), _mm_dp_ps(dist2, dist2, 0x7f));
    });
#else
	std::sort(begin(g_occluders), end(g_occluders), [&](const auto& o1, const auto& o2) {
		__m128 center1 = o1->m_center;
		__m128 center2 = o2->m_center;
		float dx1 = center1.m128_f32[0] - g_cameraPosition.m128_f32[0];
		float dy1 = center1.m128_f32[1] - g_cameraPosition.m128_f32[1];
		float dz1 = center1.m128_f32[2] - g_cameraPosition.m128_f32[2];
		float dx2 = center2.m128_f32[0] - g_cameraPosition.m128_f32[0];
		float dy2 = center2.m128_f32[1] - g_cameraPosition.m128_f32[1];
		float dz2 = center2.m128_f32[2] - g_cameraPosition.m128_f32[2];
		return dx1 * dx1 + dy1 * dy1 + dz1 * dz1 < dx2 * dx2 + dy2 * dy2 + dz2 * dz2;
	});
#endif//

BUG report:
intel 9700k win10 64bits VS2015 debug version,
while camera move far from scene app must crushed,
i speculate sort function using SSE may inaccurate so std::sort make some element ( unique_ptr ) in g_occluders to nullptr;
replace with FPU  instructions seems fix it up.

**Comment by rawrunprotected** [comment]
Thanks for reporting. I think the actual bug is due to the comile instruction (<=). This should be comilt instead (<) as required by std::sort. I will fix this as part of the next major update.
