### ISSUE TITLE
centroidAssignment should be initialized

### ISSUE THREAD

**Issue by RealJiShi** [rawrunprotected/rasterizer#3]
Occluder.cpp: 71:
```
		for (int j = 0; j < quadNormals.size(); ++j)
		{
			int k = centroidAssignment[j];
				
                        centroids[k] = _mm_add_ps(centroids[k], quadNormals[j]);
		}
```
centroidAssignment should be initialized, otherwise centroids[k] may overflow.

**Comment by rawrunprotected** [comment]
centroidAssignment should be correctly initialized in the latest version. Are you observing any crashes or unexpected behavior that would indicate otherwise?

**Comment by RealJiShi** [comment]
> centroidAssignment should be correctly initialized in the latest version. Are you observing any crashes or unexpected behavior that would indicate otherwise?

Sometimes crash due to `centroids[k]` overflow. Add a guard to access `centroids` avoids crash.
